version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:11-browsers-leagacy
    environment:
       MAVEN_OPTS: -Xmx3200m

    steps:

      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}


      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}


      - run: mvn integration-test

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar